language: node_js

node_js:
  - "node"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --ignore-scripts --ignore-engines

script:
  - yarn lint
  - yarn test
  - yarn build
